base_license: SMKQROWJNQYQSDAAAAAAAAAAAAAA 
cluster: Bucicluster
hostname: "x.x.x.100"
username: "admin"
password: "enter_you_admin_password"
https_global: "true"
validate_certs_global: "false"

hosts:
  node1:
    name: "Bucicluster-01" 
    ip: "x.x.x.101"
    aggregate: 
       name: "n1_data"
       diskcount: "7"
  node2: 
    name: "Bucicluster-02"
    ip: "x.x.x.102"
    aggregate: 
       name: "n2_data"
       diskcount: "5"    
    
license_codes: 
  - YVUCRRRRYVHXCFABGAAAAAAAAAAA 
  - WKQGSRRRYVHXCFABGAAAAAAAAAAA   
  - MBXNQRRRYVHXCFABGAAAAAAAAAAA   
  - MHEYKUNFXMSMUCEZFAAAAAAAAAAA 
  - ANGJKUNFXMSMUCEZFAAAAAAAAAAA   
  - KWZBMUNFXMSMUCEZFAAAAAAAAAAA     
  - UFNPSPZFXNVOGDAAAAAAAAAAAAAA
  - ILPASPZFXNVOGDAAAAAAAAAAAAAA


motd: "Welcome to TZAYAD Elbit Storage System. This is a monitored system! "

dns:
  - { dns_domains: hci.local, dns_nameservers: x.x.x.200, vserver: "{{ cluster }}"}
  - { dns_domains: hci.local, dns_nameservers: x.x.x.200, vserver: SVM_Beci}
  - { dns_domains: hci.local, dns_nameservers: x.x.x.200, vserver: SVM_David}

ntp:
  - { server_name: hci.local, version: auto }

snmp:
  - { community_name: ansible_snmp, access_control: ro }

ports:
  - { node: "{{hosts['node1'].name }}", port: e0d, mtu: 9000 , flowcontrol: none, autonegotiate: true}
  - { node: "{{hosts['node2'].name }}", port: e0d, mtu: 9000 , flowcontrol: none, autonegotiate: true}

ifgrps:
  - { name: a0a, node: "{{hosts['node1'].name }}", ports: "e0d", mode: multimode, mtu: 9000, distribution_function: ip }
  - { name: a0a, node: "{{hosts['node2'].name }}", ports: "e0d", mode: multimode, mtu: 9000, distribution_function: ip }

vlans:
  - { vlanid: 300, node: "{{hosts['node1'].name }}", phy_interface: "a0a" }
  - { vlanid: 400, node: "{{hosts['node1'].name }}", phy_interface: "a0a" }
  - { vlanid: 62, node: "{{hosts['node1'].name }}", phy_interface: "a0a" }
  - { vlanid: 300, node: "{{hosts['node2'].name }}", phy_interface: "a0a" }
  - { vlanid: 400, node: "{{hosts['node2'].name }}", phy_interface: "a0a" }
  - { vlanid: 62, node: "{{hosts['node2'].name }}", phy_interface: "a0a" }

bcasts:
  - { name: vlan_400, ports: "{{hosts['node1'].name }}:a0a-400,{{hosts['node2'].name }}:a0a-400", mtu: 1500 }
  - { name: vlan_300, ports: "{{hosts['node1'].name }}:a0a-300,{{hosts['node2'].name }}:a0a-300", mtu: 1500 }

vservers:
  - { name: SVM_Beci, root_volume_aggregate: "{{ hosts['node1'].aggregate.name }}" , root_volume_security_style: unix }
  - { name: SVM_David, root_volume_aggregate: "{{ hosts['node1'].aggregate.name }}" , root_volume_security_style: unix }

lifs:
  - { name: lif1, node: "{{ hosts['node1'].name }}", port: a0a-400, address: 1.1.1.1, netmask: 255.255.255.0, vserver: SVM_Beci }
  - { name: lif2, node: "{{ hosts['node2'].name }}", port: a0a-300, address: 1.1.2.2, netmask: 255.255.255.0, vserver: SVM_Beci }
  - { name: lif1, node: "{{ hosts['node2'].name }}", port: a0a-300, address: 1.3.2.2, netmask: 255.255.255.0, vserver: SVM_David }

gateway: #if a different default route/gateway then the clusters default needs to be added
  - { vserver: SVM_Beci, destination: 0.0.0.0/0, gateway: x.x.x.200 }
  - { vserver: SVM_David, destination: 0.0.0.0/0, gateway: x.x.x.200 }

cifs: # Vservers to join to an AD Domain
  - { vserver: SVM_Beci, cifs_server_name: netapp1, workgroup: hci, force: true }
  - { vserver: SVM_David, cifs_server_name: netapp2, workgroup: hci, force: true }
  
nfs: # Vservers to configure for NFS
  - { vserver: SVM_Beci, nfsv3: enabled, vstorage: enabled }
  - { vserver: SVM_David, nfsv3: enabled, vstorage: enabled }

exportrules:
  - { name: EP1, client_match: x.x.x.0/24, vserver: SVM_Beci }
  - { name: EP1, client_match: 1.1.1.0/24, vserver: SVM_Beci }
  - { name: EP1, client_match: x.x.x.0/24, vserver: SVM_David }
  - { name: EP2, client_match: 1.1.1.0/24, vserver: SVM_David }
  
volumes:
  - { name: vol1, aggr: "{{ hosts['node1'].aggregate.name }}", size: 10, policy: EP1, snappercent: 3, vserver: SVM_Beci, securitystyle: unix,  }
  - { name: vol2, aggr: "{{ hosts['node1'].aggregate.name }}", size: 10, policy: EP1, snappercent: 3, vserver: SVM_Beci, securitystyle: unix,  }
  - { name: vol3, aggr: "{{ hosts['node1'].aggregate.name }}", size: 10, policy: EP2, snappercent: 3, vserver: SVM_David, securitystyle: unix,  }
  - { name: vol4, aggr: "{{ hosts['node1'].aggregate.name }}", size: 10, policy: EP1, snappercent: 3, vserver: SVM_David, securitystyle: unix,  }

