## Replace all x.x.x.x and y.y.y.y with your IP addresses

base_license: XXXXXXXXXXXXXXXX #Optional since ontap 9.2+
cluster: BuciCluster
hostname: "x.x.x.100"
netmask: "255.255.255.0"
username: "admin"
password: "password"
https_global: "true"
validate_certs_global: "false"

hosts:
  node1:
    name: "Buciclustern1"
    ip: "x.x.x.101"
    subnet: "255.255.255.0"
    aggregate:
       name: "n1_data"
       diskcount: "10"
       raidsize: "28"
  node2:
    name: "Buciclustern2"
    ip: "x.x.x.102"
    private_ip: "169.254.114.221" #one of the private cluster ip generated
    subnet: "255.255.255.0"

licenses:
  - XXXXXXXXXXXXXXXXXXXXXXXXXXXX #Enter licene code for protocol in here
  - XXXXXXXXXXXXXXXXXXXXXXXXXXXX

motd: "Welcome to XXXXX Storage System. This is a monitored system! "

dns:
  - { dns_domains: domain.local, dns_nameservers: y.y.y.y, vserver: "{{ cluster }}"}
  - { dns_domains: domain.local, dns_nameservers: y.y.y.y, vserver: SVM_Beci}
  - { dns_domains: domain.local, dns_nameservers: y.y.y.y, vserver: SVM_David}

ntp:
  - { server_name: domain.local, version: auto }

snmp:
  - { community_name: ansible_snmp, access_control: ro }

ports:
  - { node: "{{hosts['node1'].name }}", port: e0c, mtu: 9000 , flowcontrol: none, autonegotiate: true}
  - { node: "{{hosts['node1'].name }}", port: e0d, mtu: 9000 , flowcontrol: none, autonegotiate: true}
  - { node: "{{hosts['node1'].name }}", port: e0e, mtu: 1500 , flowcontrol: none, autonegotiate: true}
  - { node: "{{hosts['node1'].name }}", port: e0f, mtu: 1500 , flowcontrol: none, autonegotiate: true}
  - { node: "{{hosts['node2'].name }}", port: e0c, mtu: 9000 , flowcontrol: none, autonegotiate: true}
  - { node: "{{hosts['node2'].name }}", port: e0d, mtu: 9000 , flowcontrol: none, autonegotiate: true}
  - { node: "{{hosts['node2'].name }}", port: e0e, mtu: 1500 , flowcontrol: none, autonegotiate: true}
  - { node: "{{hosts['node2'].name }}", port: e0f, mtu: 1500 , flowcontrol: none, autonegotiate: true}

ifgrps:
  - { name: a0a, node: "{{hosts['node1'].name }}", ports: "e0c,e0e", mode: multimode_lacp, mtu: 9000, distribution_function: ip }
  - { name: a0a, node: "{{hosts['node2'].name }}", ports: "e0c,e0e", mode: multimode_lacp, mtu: 9000, distribution_function: ip }
  - { name: a0b, node: "{{hosts['node1'].name }}", ports: "e0d,e0f", mode: multimode_lacp, mtu: 1500, distribution_function: ip }
  - { name: a0b, node: "{{hosts['node2'].name }}", ports: "e0d,e0f", mode: multimode_lacp, mtu: 1500, distribution_function: ip }


vlans:
  - { vlanid: 300, node: "{{hosts['node1'].name }}", phy_interface: "a0a" }
  - { vlanid: 400, node: "{{hosts['node1'].name }}", phy_interface: "a0a" }
  - { vlanid: 62, node: "{{hosts['node1'].name }}", phy_interface: "a0a" }
  - { vlanid: 300, node: "{{hosts['node2'].name }}", phy_interface: "a0a" }
  - { vlanid: 400, node: "{{hosts['node2'].name }}", phy_interface: "a0a" }
  - { vlanid: 62, node: "{{hosts['node2'].name }}", phy_interface: "a0a" }

bcasts:
  - { name: vlan_400, ports: "{{hosts['node1'].name }}:a0a-400,{{hosts['node2'].name }}:a0a-400", mtu: 1500 }
  - { name: vlan_300, ports: "{{hosts['node1'].name }}:a0a-300,{{hosts['node2'].name }}:a0a-300", mtu: 1500 }

vservers:
  - { name: SVM_Beci, root_volume_aggregate: "{{ hosts['node1'].aggregate.name }}" , root_volume_security_style: unix }
  - { name: SVM_David, root_volume_aggregate: "{{ hosts['node1'].aggregate.name }}" , root_volume_security_style: unix }

lifs:
  - { name: lif1, node: "{{ hosts['node1'].name }}", port: a0a-400, address: x.x.x.x, netmask: 255.255.255.0, vserver: SVM_Beci }
  - { name: lif2, node: "{{ hosts['node2'].name }}", port: a0a-300, address: x.x.x.x, netmask: 255.255.255.0, vserver: SVM_Beci }
  - { name: lif1, node: "{{ hosts['node2'].name }}", port: a0a-300, address: x.x.x.x, netmask: 255.255.255.0, vserver: SVM_David }

gateway: #if a different default route/gateway then the clusters default needs to be added
  - { vserver: SVM_Beci, destination: 0.0.0.0/0, gateway: x.x.x.254 }
  - { vserver: SVM_David, destination: 0.0.0.0/0, gateway: y.y.y.254 }

cifsad: # Vservers to join to an AD Domain
#  - { vserver: SVM_Beci, cifs_server_name: svm_beci, domain: "DOMAIN", admin_user: "USER",admin_password: "PASS", force: true } # Example 1 - Active Directory

cifsworkgroup: # Vservers to join to a local workgroup
  - { vserver: SVM_David, cifs_server_name: netapp2, workgroup: test, force: true }


nfs: # Vservers to configure for NFS
  - { vserver: SVM_Beci, nfsv3: enabled, vstorage: enabled }
  - { vserver: SVM_David, nfsv3: enabled, vstorage: enabled }

exportrules:
  - { name: EP1, client_match: x.x.x.0/24, vserver: SVM_Beci }
  - { name: EP2, client_match: x.x.x.0/24, vserver: SVM_David }

volumes:
  - { name: vol1, aggr: "{{ hosts['node1'].aggregate.name }}", size: 10, policy: EP1, snappercent: 3, vserver: SVM_Beci, securitystyle: unix  }
  - { name: vol2, aggr: "{{ hosts['node1'].aggregate.name }}", size: 10, policy: EP1, snappercent: 3, vserver: SVM_Beci, securitystyle: unix  }
  - { name: vol3, aggr: "{{ hosts['node1'].aggregate.name }}", size: 10, policy: EP2, snappercent: 3, vserver: SVM_David, securitystyle: unix  }
  - { name: vol4, aggr: "{{ hosts['node1'].aggregate.name }}", size: 10, policy: EP1, snappercent: 3, vserver: SVM_David, securitystyle: unix  }

sp:
  - { node: "{{ hosts['node1'].name }}", dhcp: none, ip_enabled: true, address_type: ipv4, state: present, ip_address: x.x.x.x, netmask: 255.255.255.0, gateway: x.x.x.x }
  - { node: "{{ hosts['node2'].name }}", dhcp: none, ip_enabled: true, address_type: ipv4, state: present, ip_address: x.x.x.x, netmask: 255.255.255.0, gateway: x.x.x.x }

